name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - Makefile
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - Makefile

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
